version: '3.8'

#services:
#  cassandra:
#    image: cassandra:4.0
#    ports:
#      - 9042:9042
#    volumes:
#      - ~/apps/cassandra:/var/lib/cassandra
#    environment:
#      - CASSANDRA_CLUSTER_NAME=cloudinfra

services:
  cassandra:
    image: cassandra:4.1.1
    ports:
      - 9042:9042
    environment:
      - CASSANDRA_CLUSTER_NAME=akka-cassandra-cluster

#  postgres:
#    image: postgres
#    restart: always
#    environment:
#      - DATABASE_HOST=127.0.0.1
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_DB=finance-db
#    ports:
#      - '5432:5432'
#    volumes:
#      - ./sql/V1_0_0_0__create_tables.sql:/docker-entrypoint-initdb.d/V1_0_0_0__create_tables.sql
#      - postgres:/var/lib/postgresql/data

#  pgadmin-compose:
#    image: dpage/pgadmin4
#    environment:
#        PGADMIN_DEFAULT_EMAIL: "test@gmail.com"
#        PGADMIN_DEFAULT_PASSWORD: "test123!"
#    ports:
#        - "16543:80"
#    depends_on:
#        - postgres
volumes:
  postgres:
    driver: local