--
-- Add Categories to the table Category

INSERT INTO category(id, name, description, is_active, parent_id)
VALUES (1, 'SERVICIOS BASICOS', 'Pagos que se realizan mensualmente', true, NULL),
(2, 'Luz', NULL, true, 1),
(3, 'Agua', NULL, true, 1),
(4, 'Gas', NULL, true, 1),
(5, 'Telefono', NULL, true, 1),
(6, 'Internet', NULL, true, 1),
(7, 'DEUDAS', '', true, NULL),
(8, 'Seguro Medico', NULL, true, 7),
(9, 'Servico Funeral', NULL, true, 7),
(10, 'Tarjeta de Credito', NULL, true, 7),
(11, 'Ortodoncia', NULL, true, 7),
(12, 'AUTOMOVIL', 'Pagos o gastos relacionados al auto', true, NULL),
(13, 'Lavado', '', true, 12),
(14, 'Seguro', '', true, 12),
(15, 'Parqueo', '', true, 12),
(16, 'Reparaciones', '', true, 12),
(17, 'Licencia / Tramites', '', true, 12),
(18, 'Impuestos', '', true, 12),
(19, 'Otros', '', true, 12),
(20, 'SEGUROS', '', true, NULL),
(21, 'Seguro de Vida', '', true, 20),
(22, 'EDUCACION', '', true, NULL),
(23, 'Guarderia - material escolar', '', true, 22),
(24, 'Guarderia - Mensualidad', '', true, 22),
(25, 'Guarderia - libros', '', true, 22),
(26, 'Libros', '', true, 22),
(27, 'Cursos', '', true, 22),
(28, 'TRANSPORTE', '', true, NULL),
(29, 'Bus', '', true, 28),
(30, 'Teleferico', '', true, 28),
(31, 'Taxi', '', true, 28),
(32, 'SALARIOS', '', true, NULL),
(33, 'Sueldo', '', true, 32),
(34, 'Adelanto', '', true, 32),
(35, 'Finiquito', '', true, 32),
(36, 'Retroactivo', '', true, 32),
(37, 'FINES DE SEMANA', 'Gastos se realizan un fin de semana o feriado', true, NULL),
(38, 'Helado', '', true, 37),
(39, 'Hamburguesa', '', true, 37),
(40, 'Pollo', '', true, 37),
(41, 'Pizza', '', true, 37),
(42, 'Parrilla', '', true, 37),
(43, 'Restaurant', '', true, 37),
(44, 'Masita', '', true, 37),
(45, 'otros', '', true, 37),
(46, 'SALUD', '', true, NULL),
(47, 'Medicamento', '', true, 46),
(48, 'Vitaminas', '', true, 46),
(49, 'Pediatra', '', true, 46),
(50, 'Vucuna', '', true, 46),
(51, 'Otros', '', true, 46),
(52, 'MASCOTAS', '', true, NULL),
(53, 'Arena', '', true, 52),
(54, 'Croquetas', '', true, 52),
(55, 'Veterinario', '', true, 52),
(56, 'Vacunas', '', true, 52),
(57, 'Otros', '', true, 52),
(58, 'CUMPLE Y DIAS ESPECIALES', '', true, NULL),
(59, 'Torta', '', true, 58),
(60, 'Regalos', '', true, 58),
(61, 'Flores', '', true, 58),
(62, 'Otros', '', true, 58),
(63, 'OTROS GASTOS', '', true, NULL),
(64, 'Otros', '', true, 63),
(65, 'ALIMENTOS', '', true, NULL),
(66, 'Carne de Res', '', true, 65),
(67, 'Carne de Pollo', '', true, 65),
(68, 'Verduras', '', true, 65),
(69, 'Frutas', '', true, 65),
(70, 'Huevo', '', true, 65),
(71, 'Leche', '', true, 65),
(72, 'Queso', '', true, 65),
(73, 'Yogurt', '', true, 65),
(74, 'Cereales', '', true, 65),
(75, 'Fideos', '', true, 65),
(76, 'Agua', '', true, 65),
(77, 'Otros', '', true, 65);